// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYhEk9x7x4-brZnattHmD6Nbmxmib6uv4',
    appId: '1:522817529604:web:5dfc8ca26d97e0a7cfd251',
    messagingSenderId: '522817529604',
    projectId: 'mislab3-f0dba',
    authDomain: 'mislab3-f0dba.firebaseapp.com',
    storageBucket: 'mislab3-f0dba.firebasestorage.app',
    measurementId: 'G-RSMDPGS6M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2PtFgLUpwlsQq8Tx2MMEFPImLruZE3J0',
    appId: '1:522817529604:android:678a3559c4bd82b0cfd251',
    messagingSenderId: '522817529604',
    projectId: 'mislab3-f0dba',
    storageBucket: 'mislab3-f0dba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2bTYbL3MRUU9xL40aPT4b7VcdwMzwKOg',
    appId: '1:522817529604:ios:28299e5fae632d6fcfd251',
    messagingSenderId: '522817529604',
    projectId: 'mislab3-f0dba',
    storageBucket: 'mislab3-f0dba.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2bTYbL3MRUU9xL40aPT4b7VcdwMzwKOg',
    appId: '1:522817529604:ios:28299e5fae632d6fcfd251',
    messagingSenderId: '522817529604',
    projectId: 'mislab3-f0dba',
    storageBucket: 'mislab3-f0dba.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYhEk9x7x4-brZnattHmD6Nbmxmib6uv4',
    appId: '1:522817529604:web:e57e415edf536e53cfd251',
    messagingSenderId: '522817529604',
    projectId: 'mislab3-f0dba',
    authDomain: 'mislab3-f0dba.firebaseapp.com',
    storageBucket: 'mislab3-f0dba.firebasestorage.app',
    measurementId: 'G-N6K1CTV7F0',
  );

}